[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85.1"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
perf = { level = "deny", priority = -1 }

allow_attributes_without_reason = "deny"
branches_sharing_code = "warn"
collapsible_else_if = "deny"
incompatible_msrv = "forbid"
needless_return = "allow"
new_without_default = "warn"
use_self = "deny"

[profile.release]
lto = true
codegen-units = 1

[workspace.dependencies]
rshell-cli = { path = "crates/rshell-cli" }
rshell-runtime = { path = "crates/rshell-runtime" }

tokio = "1.52.3"

clap = "4.6.1"
mlua = "0.11.6"

# Logging
log = "0.4.33"
colog = "1.4.0"

# Data structures
parking_lot = "0.12.5"

# Utils
colored = "3.1.1"
getset = "0.1.7"
strum = "0.28.0"
thiserror = "2.0.18"
