[package]
name = "rshell-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
mlua = { workspace = true, features = ["luau", "async", "send"] }
tokio = { workspace = true, features = ["rt", "parking_lot", "time"] }
log.workspace = true
parking_lot.workspace = true
getset.workspace = true
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true
